CREATE TABLE LIST_ITEMS (
    id SERIAL PRIMARY KEY,
    list_id INT NOT NULL,
    item_id INT NOT NULL,
    added_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (list_id) REFERENCES LISTA (id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES ITEMS (id) ON DELETE CASCADE
);
